v3

diff --git a/openstack-etc b/openstack-etc
--- a/openstack-etc
+++ b/openstack-etc
@@ -1,10 +1,33 @@
 #!/bin/sh
 
+# this is a line to retrieve admin's token from diablo keystone database
+# mysql -unova -pnova keystone -e "select id from token where user_id = (select id from users where name='admin' limit 1) order by expires desc limit 1;" -B | tail -1
+    
+function get_date() {
+    date '+%Y.%m.%d-%H.%M'
+}
 
-function setup_keystone_auth() {
-    sed -i 's#%SERVICE_TENANT_NAME%#systenant#' "$@"
-    sed -i 's#%SERVICE_USER%#admin#' "$@"
-    sed -i "s#%SERVICE_PASSWORD%#${ADMIN_PASSWORD}#" "$@"
+function guess_release() {
+    if [ ! -r /etc/nova/nova.conf ]; then
+        echo "Cannot guess openstack release. Please check your /etc/nova/nova.conf" >&2
+        echo "unknown"
+        return 1
+    fi
+    grep -q "^--" /etc/nova/nova.conf && echo "diablo" || echo "essex"    
+}
+
+function do_essex_setup() {
+    sed -i 's#^sql_connection.*#sql_connection = mysql://nova:nova@main-node/glance#' /etc/glance/glance-registry.conf 
+    sed -i 's#^sql_connection.*#sql_connection = mysql://nova:nova@main-node/nova#' /etc/nova/nova.conf 
+    sed -i 's#^connection.*#connection = mysql://nova:nova@main-node/keystone#' /etc/keystone/keystone.conf 
+    sed -i 's#localhost#main-node#' /etc/keystone/default_catalog.templates 
+
+    KEYSTONE_CLIENTS=$(echo /etc/glance/glance-{registry,api}-paste.ini /etc/nova/api-paste.ini)
+    ADMIN_PASSWORD=$(uuidgen)
+    echo "keystone ADMIN_PASSWORD is ${ADMIN_PASSWORD}"
+    sed -i 's#%SERVICE_TENANT_NAME%#systenant#' $KEYSTONE_CLIENTS
+    sed -i 's#%SERVICE_USER%#admin#' $KEYSTONE_CLIENTS
+    sed -i "s#%SERVICE_PASSWORD%#${ADMIN_PASSWORD}#" $KEYSTONE_CLIENTS
 }
 
 function keystone_client() {
@@ -19,28 +42,13 @@ function get_id() {
     echo $line | while read a id c; do echo $id; done
 }
 
-function setup() {
-    ADMIN_PASSWORD=$(uuidgen)
-    echo "keystone ADMIN_PASSWORD is ${ADMIN_PASSWORD}"
-
-    cd /etc/glance
-    sed -i 's#^sql_connection.*#sql_connection = mysql://nova:nova@main-node/glance#' glance-registry.conf 
-    setup_keystone_auth glance-{registry,api}-paste.ini
-    echo "glance config is updated"
-
-    cd /etc/nova
-    sed -i 's#^sql_connection.*#sql_connection = mysql://nova:nova@main-node/nova#' nova.conf 
-    setup_keystone_auth api-paste.ini
-    echo "nova config is updated"
-
-    cd /etc/keystone/
-    sed -i 's#^connection.*#connection = mysql://nova:nova@main-node/keystone#' keystone.conf 
-    sed -i 's#localhost#main-node#' default_catalog.templates 
-    echo "keystone config is updated"
+function do_essex_keystone_db() {
+    ADMIN_PASSWORD=$(grep admin_password /etc/nova/api-paste.ini | sed -r 's/^.*\s(\S+)\s*$/\1/')
+    echo "setting keystone ADMIN_PASSWORD to ${ADMIN_PASSWORD}"
 
     /etc/init.d/keystone restart
-    get_id tenant systenant || keystone_client tenant-create --name systenant
-    get_id role Admin || keystone_client role-create --name Admin
+    get_id tenant systenant >/dev/null || keystone_client tenant-create --name systenant
+    get_id role Admin >/dev/null || keystone_client role-create --name Admin
     ADMIN_USER_ID=$(get_id user admin)
     if [ -n "$ADMIN_USER_ID" ]; then
         keystone_client user-password-update --pass "$ADMIN_PASSWORD" "$ADMIN_USER_ID"
@@ -52,15 +60,38 @@ function setup() {
     echo "admin user is updated"
 }
 
-function purge() {
+function do_diablo_setup() {
+    sed -i 's#^sql_connection.*#sql_connection = mysql://nova:nova@main-node/glance#' /etc/glance/glance-registry.conf 
+    sed -i 's#^--sql_connection.*#--sql_connection=mysql://nova:nova@main-node/nova#' /etc/nova/nova.conf
+    sed -i 's#^sql_connection.*#sql_connection = mysql://nova:nova@main-node/keystone#' /etc/keystone/keystone.conf
+
+    cp /etc/keystone/nova-api-paste.ini /etc/nova/api-paste.ini
+    sed -i 's#^pipeline.*apiv1app.*$#pipeline = versionnegotiation authtoken auth-context apiv1app#' /etc/glance/glance-api.conf
+    sed -i 's#^pipeline.*registryapp.*$#pipeline = authtoken auth-context registryapp#' /etc/glance/glance-registry.conf
+
+    KEYSTONE_CLIENTS=$(echo /etc/glance/glance-{registry,api}.conf /etc/nova/api-paste.ini)
+    ADMIN_TOKEN=$(uuidgen)
+    echo "keystone ADMIN_TOKEN is ${ADMIN_TOKEN}"
+    sed -i "s#999888777666#${ADMIN_TOKEN}#" $KEYSTONE_CLIENTS
+}
+
+function do_diablo_keystone_db() {
+    ADMIN_TOKEN=$(grep admin_token /etc/nova/api-paste.ini | sed -r 's/^.*\s(\S+)\s*$/\1/')
+    echo "setting keystone ADMIN_TOKEN to ${ADMIN_TOKEN}"
+
+    mysql -unova -pnova keystone -e "insert into token (id, user_id, tenant_id, expires) values ('${ADMIN_TOKEN}', 1, 1, '2015-01-01 00:00:00');"
+    /etc/init.d/keystone restart
+}
+
+function do_purge() {
     rm -rfv /etc/{glance,nova,keystone}
 }
 
-function save() {
-    tar -cvzf ${1:-.}/openstack-etc.$(date '+%Y.%m.%d-%R').tar.gz /etc/{glance,nova,keystone}
+function do_save() {
+    tar -cvzf "${1:-.}/openstack-etc.$(get_date).tar.gz" /etc/{glance,nova,keystone}
 }
 
-function unpack() {
+function do_unpack() {
     tar -xvf "$1" -C /
 }
 
@@ -70,21 +101,23 @@ shift
 
 case "$ACTION" in
     save)
-        save
+        do_save
 	;;
     replace)
-	purge
-	unpack "$@"
+	do_purge
+	do_unpack "$@"
 	;;
     purge)
-	purge
+	do_purge
 	;;
-    setup)
-        setup
+    setup|keystone_db)
+        release="$(guess_release)"
+        [ "x$?" != "x0" ] && exit 1
+        echo "$ACTION for $release"
+        "do_${release}_${ACTION}"
         ;;
     *)
-        echo "Usage: $0 (save|replace|purge|setup)"
+        echo "Usage: $0 (save|replace|purge|setup|keystone_db)"
         exit 1
         ;;
-
 esac
